# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 22:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelApp', '0003_trip_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='created_by',
        ),
    ]
